import Link from 'next/link'
import './globals.css'
import Control from './Control';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const data = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache:'no-store'});
  const topics = await data.json();

  

  return (
    <html lang="en">
      <body>
        <h1>
          <Link href='/'>WEB</Link>
        </h1>
        <ul>
          {
            topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })
          }
        </ul>
        {children}
        <Control />
        </body>
    </html>
  )
}
